### PR TITLE
Feature: add build target for ESP32S3.

### PR DESCRIPTION
**Pull request by aentinger**
The ESP32S3 is used on the Arduino Nano ESP32 which is also used as central processing unit for the Arduino Alvik Robot.

A PR adding a micros-ROS based firmware to the Arduino Alvik can be found here: https://github.com/arduino-libraries/Arduino_Alvik/pull/7 .

### CODE REVIEW

**Comment by aentinger** [comment]
Wow, thank you @pablogs9 - that was merged fast. Shall I prepare a similar PR against `jazzy` or what is your preferred approach here?

**Comment by pablogs9** [comment]
@mergify backport jazzy iron rolling

**Comment by pablogs9** [comment]
@aentinger it seems that Mergify is struggling with this backport... Could you open this very same PR for jazzy iron rolling please?

**Comment by aentinger** [comment]
>could you open this very same PR for jazzy iron rolling please?

Done :bow:

**Pull request merged**
