### PR TITLE
Add Arduino Portenta H7 platformio setup instructions

### PR DESCRIPTION
**Pull request by amilcarlucas**
This would have saved me two days work

### CODE REVIEW

**Comment by pablogs9** [comment]
Just for info: this is an ROS 2 issue because the generate the same symbols if two `.msg` are named equally. For example, if we search in the `.a` file for the duplicated symbol this is the situation:

In Galactic:
```bash
➜  micro_ros_arduino git:(galactic) nm -A '/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a' | grep Empty__rosidl_typesupport_introspection_c__Empty_fini_function
/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a:libexample_interfaces__rosidl_typesupport_introspection_c-empty__type_support.c.obj:00000001 T Empty__rosidl_typesupport_introspection_c__Empty_fini_function
/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a:libstd_msgs__rosidl_typesupport_introspection_c-empty__type_support.c.obj:00000001 T Empty__rosidl_typesupport_introspection_c__Empty_fini_function
```

Symbol `Empty__rosidl_typesupport_introspection_c__Empty_fini_function` is defined both in `example_interfaces` and in `std_msgs`, because both have `Empty.msg`

In Rolling we have fixed it:
```bash
➜  micro_ros_arduino git:(main) nm -A '/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a' | grep Empty__rosidl_typesupport_introspection_c__Empty_fini_function
/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a:libexample_interfaces__rosidl_typesupport_introspection_c-empty__type_support.c.obj:00000001 T example_interfaces__msg__Empty__rosidl_typesupport_introspection_c__Empty_fini_function
/home/pgarrido/Arduino/libraries/micro_ros_arduino-0.0.1/src/cortex-m7/fpv5-d16-softfp/libmicroros.a:libstd_msgs__rosidl_typesupport_introspection_c-empty__type_support.c.obj:00000001 T std_msgs__msg__Empty__rosidl_typesupport_introspection_c__Empty_fini_function
```

And now symbols are prepended with the packet name. See `example_interfaces__msg__Empty__rosidl_typesupport_introspection_c__Empty_fini_function` vs `std_msgs__msg__Empty__rosidl_typesupport_introspection_c__Empty_fini_function`

**This means that this PR should not be backported to main (Rolling)**

**Comment by pablogs9** [comment]
Also @Acuadros95 can we generalize these instructions in order to work in any platform when using Platform.io?

**Review by pablogs9 — APPROVED** [review]

**Comment by Acuadros95** [comment]
@pablogs9 I dont think we can archive generic instructions for platformio builds. Depending on the board we need to set a specific compiler version, modify the board platform commit, or add this linker fix

Maybe we can add a platformio known issues section.

**Comment by pablogs9** [comment]
What about a generic `platformio.ini` and different `fix_linker.py` for each platform?

I agree with including it in known issues instead in general instructions because this will be not needed in future releases

**Comment by Acuadros95** [comment]
Moved to: https://github.com/micro-ROS/micro_ros_arduino/pull/849

**Pull request closed without merging**
