### PR TITLE
Add support for Portenta H7

### PR DESCRIPTION
**Pull request by lukicdarkoo**
This PR adds support Portenta H7:
https://store.arduino.cc/portenta-h7

This thing has Wi-Fi, so I will maybe add an example later.

### CODE REVIEW

**Comment by pablogs9** [comment]
Hello, @lukicdarkoo I guess that we have duplicated the work. Check https://github.com/micro-ROS/micro_ros_arduino/tree/feature/portenta_support.

I'm going to compare our branches and merge a common version. I don't have a Portenta board here, is possible for you to test the final version.

Another point that I'm seeing is that your port only supports the M7, what do you think about supporting both M7 and M4?

**Comment by pablogs9** [comment]
Hello @lukicdarkoo, I have been checking my branch and modifying it to match some of your approaches.

I have one question, why are you adding this?

```c
int usleep(useconds_t usec) {
    return delayMicroseconds(usec);
}
```

I'm able to build examples without it for the same platform.

Please check this PR https://github.com/micro-ROS/micro_ros_arduino/pull/65 and let me know if you are ok with merging this other PR instead of this one. If you could test it on your board it would be great.

**Comment by lukicdarkoo** [comment]
> Hello, @lukicdarkoo I guess that we have duplicated the work. Check https://github.com/micro-ROS/micro_ros_arduino/tree/feature/portenta_support.

Ups, sorry, I completely missed it :( Why isn't it merge to the main branch?

I will check the old branch and let you whether it works for me

**Comment by pablogs9** [comment]
You can comment in this PR if you want to modify something: https://github.com/micro-ROS/micro_ros_arduino/pull/65

**Comment by pablogs9** [comment]
Closing due to https://github.com/micro-ROS/micro_ros_arduino/pull/65

**Pull request closed without merging**
