### PR TITLE
Add platformio known issues to Readme

### PR DESCRIPTION
**Pull request by Acuadros95**
TODO: Backport without ***`multiple definition of` Link errors on galactic*** section

### CODE REVIEW

**Comment by Acuadros95** [comment]
Please @amilcarlucas give your thoughts

**Review by pablogs9 — APPROVED** [review]
LGTM

**Comment by Acuadros95** [comment]
@mergify backport main foxy

**Comment by pablogs9** [comment]
Do we need this in galactic and foxy?

**Comment by Acuadros95** [comment]
On rolling and foxy we don't need the linker modifications, but the rest of issues still apply

**Review by amilcarlucas — APPROVED** [review]

**Comment by amilcarlucas** [comment]
Yes, I like the way you changed it. Thanks for following up on this.

**Pull request merged**
